### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by Morayabb** [ShuGuoJ/SQformer#1]
Hello, thank you very much for your excellent work! If possible, could you please advise on how to obtain the data involved in this article? Thank you.

**Comment by ShuGuoJ** [comment]
The data used in the paper can be downloaded from https://naotoyokoya.com/Download.html. Thank you very much for acknowledging our work.

**Comment by Morayabb** [comment]
> The data used in the paper can be downloaded from https://naotoyokoya.com/Download.html. Thank you very much for acknowledging our work.

Thank you very much for your reply. If possible, could you please provide detailed steps for data processing or reference materials? Looking forward to your reply.
